# Azure DevOps
# CI pipeline for PSDocs

variables:
  version: '0.7.0'
  buildConfiguration: 'Release'

 # Use build number format, i.e. 0.1.0-B1811001
name: $(version)-B$(date:yyMM)$(rev:rrr)

trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - 'v0.*'

pr:
  branches:
    include:
    - 'master'

stages:

# Build pipeline
- stage: Build
  displayName: Build
  jobs:
  - job:
    strategy:
      matrix:
        Linux:
          displayName: 'Linux'
          imageName: 'ubuntu-18.04'
        MacOS:
          displayName: 'MacOS'
          imageName: 'macOS-10.15'
        Windows:
          displayName: 'Windows'
          imageName: 'vs2017-win2016'
          publish: 'true'
          analysis: 'true'
          coverage: 'true'
    pool:
      vmImage: $(imageName)
    displayName: 'PowerShell'
    steps:

    # Install pipeline dependencies
    - powershell: ./.azure-pipelines/pipeline-deps.ps1
      displayName: 'Install dependencies'

    # Build module
    - powershell: Invoke-Build -Configuration $(buildConfiguration) -Build $(Build.BuildNumber)
      displayName: 'Build module'
      timeoutInMinutes: 15

    # Pester test results
    - task: PublishTestResults@2
      displayName: 'Publish Pester results'
      inputs:
        testRunTitle: 'Pester on $(imageName)'
        testRunner: NUnit
        testResultsFiles: 'reports/pester-unit.xml'
        mergeTestResults: true
        platform: $(imageName)
        configuration: $(buildConfiguration)
        publishRunAttachments: true
      condition: succeededOrFailed()

    # PSRule results
    # - task: PublishTestResults@2
    #   displayName: 'Publish PSRule results'
    #   inputs:
    #     testRunTitle: 'PSRule on $(imageName)'
    #     testRunner: NUnit
    #     testResultsFiles: 'reports/rule.report.xml'
    #     mergeTestResults: true
    #     platform: $(imageName)
    #     configuration: $(buildConfiguration)
    #     publishRunAttachments: true
    #   condition: succeededOrFailed()

    # Publish Code Coverage Results
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Pester code coverage'
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: 'reports/pester-coverage.xml'
      condition: eq(variables['coverage'], 'true')

    # Generate artifacts
    - task: PublishPipelineArtifact@0
      displayName: 'Publish module'
      inputs:
        artifactName: PSDocs
        targetPath: out/modules/PSDocs
      condition: and(succeeded(), eq(variables['publish'], 'true'))

# Release pipeline
- stage: Release
  displayName: Release
  dependsOn: Build
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v0.')
  jobs:
  - job:
    displayName: Live
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: DownloadPipelineArtifact@1
      displayName: 'Download module'
      inputs:
        artifactName: PSDocs
        downloadPath: $(Build.SourcesDirectory)/out/modules/PSDocs
    # Install pipeline dependencies
    - powershell: ./.azure-pipelines/pipeline-deps.ps1
      displayName: 'Install dependencies'
    # Install pipeline dependencies and build module
    # - powershell: Invoke-Build Release -ApiKey $(apiKey)
    #   displayName: 'Publish module'
