//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSDocs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PSDocsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PSDocsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSDocs.Resources.PSDocsResources", typeof(PSDocsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target failed Type precondition.
        /// </summary>
        internal static string DebugTargetTypeMismatch {
            get {
                return ResourceManager.GetString("DebugTargetTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find required parameter &apos;{0}&apos; for definition at {1}..
        /// </summary>
        internal static string DefinitionParameterNotFound {
            get {
                return ResourceManager.GetString("DefinitionParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSDocs][D] -- Found {0} PSDocs module(s).
        /// </summary>
        internal static string FoundModules {
            get {
                return ResourceManager.GetString("FoundModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The included file was not found..
        /// </summary>
        internal static string IncludeNotFound {
            get {
                return ResourceManager.GetString("IncludeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document nesting was detected for definition at {0}. Definitions must not be nested..
        /// </summary>
        internal static string InvalidDocumentNesting {
            get {
                return ResourceManager.GetString("InvalidDocumentNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid ErrorAction ({0}) was specified for definition at {1}. Ignore | Stop are supported..
        /// </summary>
        internal static string InvalidErrorAction {
            get {
                return ResourceManager.GetString("InvalidErrorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A culture must be specified when no culture is specified by the system. To specify a culture use the &apos;Output.Culture&apos; option..
        /// </summary>
        internal static string InvariantCulture {
            get {
                return ResourceManager.GetString("InvariantCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A label must be set..
        /// </summary>
        internal static string LabelNullOrEmpty {
            get {
                return ResourceManager.GetString("LabelNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options file does not exist..
        /// </summary>
        internal static string OptionsNotFound {
            get {
                return ResourceManager.GetString("OptionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read JSON failed..
        /// </summary>
        internal static string ReadJsonFailed {
            get {
                return ResourceManager.GetString("ReadJsonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSDocs][D] -- Scanning for source files in module: {0}.
        /// </summary>
        internal static string ScanModule {
            get {
                return ResourceManager.GetString("ScanModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSDocs][D] -- Scanning for source files: {0}.
        /// </summary>
        internal static string ScanSource {
            get {
                return ResourceManager.GetString("ScanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script was not found..
        /// </summary>
        internal static string ScriptNotFound {
            get {
                return ResourceManager.GetString("ScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSDocs][S][Trace] -- {0}: {1} {0} {2}.
        /// </summary>
        internal static string SelectorExpressionTrace {
            get {
                return ResourceManager.GetString("SelectorExpressionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSDocs][S][Trace] -- {0}.
        /// </summary>
        internal static string SelectorMatchTrace {
            get {
                return ResourceManager.GetString("SelectorMatchTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector &apos;{0}&apos; specified for definition at {1} could not be found..
        /// </summary>
        internal static string SelectorNotFound {
            get {
                return ResourceManager.GetString("SelectorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSDocs][S][Trace] -- {0}: {1}.
        /// </summary>
        internal static string SelectorTrace {
            get {
                return ResourceManager.GetString("SelectorTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not serialize a null PSObject..
        /// </summary>
        internal static string SerializeNullPSObject {
            get {
                return ResourceManager.GetString("SerializeNullPSObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create path.
        /// </summary>
        internal static string ShouldCreatePath {
            get {
                return ResourceManager.GetString("ShouldCreatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write file.
        /// </summary>
        internal static string ShouldWriteFile {
            get {
                return ResourceManager.GetString("ShouldWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source was not found..
        /// </summary>
        internal static string SourceNotFound {
            get {
                return ResourceManager.GetString("SourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified document title is empty and will be skipped..
        /// </summary>
        internal static string TitleEmpty {
            get {
                return ResourceManager.GetString("TitleEmpty", resourceCulture);
            }
        }
    }
}
